name : CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      artifact:
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradle
        run: chmod +x gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check current directory contents
        run: ls -l

      - name: Check ip
        run: curl ifconfig.me

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifact }}
          path: ./build/libs/${{ env.artifact }}

      - name: run main
        run: java -jar ./build/libs/${{ env.artifact }}